### ISSUE TITLE
Compatibility: Works great on Neptune 2

### ISSUE THREAD

**Issue by Toylerrr** [daniel-kukiela/LotmaxxSnapshot#1]
Seems as if this will work on all printers with MKS robin nano 1.2 boards too. Tested it on my stock Neptune 2 works great!

**Comment by daniel-kukiela** [comment]
Sorry, I must have missed your message earlier.

Thank you for your feedback and testing. Hmm, I might add this info to the description.

**Comment by daniel-kukiela** [comment]
Updated readme to include some into about MKS boards. Thank you!
