### ISSUE TITLE
Add Cura 5.x.x Support

### ISSUE THREAD

**Issue by Garywoo** [daniel-kukiela/LotmaxxSnapshot#2]
It appears this plugin is no longer working in the latest [Cura 5.0.0 Beta](https://github.com/Ultimaker/Cura/releases/tag/5.0-beta).

Please could support be added? This is such a handy plugin.

**Comment by daniel-kukiela** [comment]
Hi,

I will take a look at this in the coming days. I need to figure out the changes.

**Comment by daniel-kukiela** [comment]
Just updated the plugin. I made a quick test and it seems to be working in Cura 5. Can you, please, verify and let me know?

**Comment by Garywoo** [comment]
It works! Tested on Cura 5.0.0.

Thanks for the quick fix!
